<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />

<meta name="author" content="Jennifer Teed" />


<title>Reproducible Research: Peer Assessment 1</title>

<script src="PA1_template_files/jquery-1.11.0/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="PA1_template_files/bootstrap-3.3.1/css/bootstrap.min.css" rel="stylesheet" />
<script src="PA1_template_files/bootstrap-3.3.1/js/bootstrap.min.js"></script>
<script src="PA1_template_files/bootstrap-3.3.1/shim/html5shiv.min.js"></script>
<script src="PA1_template_files/bootstrap-3.3.1/shim/respond.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<link rel="stylesheet"
      href="PA1_template_files/highlight/default.css"
      type="text/css" />
<script src="PA1_template_files/highlight/highlight.js"></script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img { 
  max-width:100%; 
  height: auto; 
}
</style>
<div class="container-fluid main-container">


<div id="header">
<h1 class="title">Reproducible Research: Peer Assessment 1</h1>
<h4 class="author"><em>Jennifer Teed</em></h4>
<h4 class="date"><em>June 7, 2015</em></h4>
</div>


<p>This assignment answers a number of questions about the Activity Monitoring Data dataset (included in the git repository). Below I document the questions as well as the steps taken to answer them. Because I used RStudio, the knitr package was built into the environment.</p>
<div id="loading-and-preprocessing-the-data" class="section level2">
<h2>Loading and preprocessing the data</h2>
<pre class="r"><code># save all images to the figures directory

# unzip the file
file &lt;- unzip(&quot;activity.zip&quot;)

# set up the names and data types of the columns and then load the data
df&lt;- read.csv(&quot;activity.csv&quot;, na.strings=&quot;NA&quot;, 
             col.names=c(&quot;steps&quot;, &quot;date&quot;, &quot;interval&quot;), 
             colClasses=c(&quot;integer&quot;, &quot;Date&quot;, &quot;integer&quot;))

#used to report the number of observations in the dataset below.
len &lt;- length(df$date)</code></pre>
<p>The variables included in this dataset are:</p>
<ul>
<li><p>steps: Number of steps taking in a 5-minute interval (with missing values are coded as NA )</p></li>
<li><p>date: The date on which the measurement was taken in YYYY-MM-DD format</p></li>
<li><p>interval: Identifier for the 5-minute interval in which measurement was taken</p></li>
</ul>
<p>The dataset is stored in a comma-separated-value (CSV) file and there are a total of 17568 observations in this dataset.</p>
<pre class="r"><code># take a peek at the data to verify it loaded properly
#head(df)</code></pre>
</div>
<div id="what-is-the-mean-of-the-total-number-of-steps-taken-per-day" class="section level2">
<h2>What is the mean of the total number of steps taken per day?</h2>
<p>For this part of the assignment, I ignore the missing values in the dataset.</p>
<div id="calculate-the-total-number-of-steps-taken-per-day." class="section level3">
<h3>1.Calculate the total number of steps taken per day.</h3>
<pre class="r"><code># Calculate the number of steps taken, per day, and put the answers into a vector.
v &lt;- aggregate(df[, 1],list(df$date), sum, na.rm=TRUE)
colnames(v) &lt;- c(&quot;date&quot;, &quot;total.steps&quot;)</code></pre>
<p>The total number of steps taken per day is in v$total.steps.</p>
</div>
<div id="make-a-histogram-of-the-total-number-of-steps-taken-each-day." class="section level3">
<h3>2.Make a histogram of the total number of steps taken each day.</h3>
<pre class="r"><code>hist(v[ , 2], 
     breaks=10, 
     xlab=&quot;Total Steps Reported in the Day&quot;, 
     main=&quot;Histogram of total number of steps taken each day&quot;)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-4-1.png" /></p>
<p>From this data we can see, that for about half of the days in the reporting period, the person took between ten and fifteen thousand steps per day.</p>
</div>
<div id="calculate-and-report-the-mean-and-median-of-the-total-number-of-steps-taken-per-day" class="section level3">
<h3>3.Calculate and report the mean and median of the total number of steps taken per day</h3>
<pre class="r"><code># You could use summary here instead to get the answers, but then you can&#39;t plug the answers back into the 
# text below. Doing both here to double check answers
summary(v$total.steps)[c(3,4)]</code></pre>
<pre><code>## Median   Mean 
##  10400   9354</code></pre>
<pre class="r"><code>meanVal &lt;- signif(mean(v[ , 2]), 4 )
medianVal &lt;- median(v[ , 2])</code></pre>
<p>The mean total number steps taken per day is: <em>9354</em>.</p>
<p>The median total number steps taken per day is: <em>10395</em>.</p>
<p>The difference between my computed values and the values reported by summary are due to rounding and/or signifiant digits.</p>
</div>
</div>
<div id="what-is-the-average-daily-activity-pattern" class="section level2">
<h2>What is the average daily activity pattern?</h2>
<div id="make-a-time-series-plot-i.e.-type-l-of-the-5-minute-interval-x-axis-and-the-average-number-of-steps-taken-averaged-across-all-days-y-axis" class="section level3">
<h3>1.Make a time series plot (i.e. type = “l” ) of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)</h3>
<pre class="r"><code># save the intervals as a unique list, similar to a factor, for later use
# the format of the interval is HHMM, in 5 minute increments, so 100 is 1 hour, 0 minutes
interval.list &lt;- unique(df$interval)

# group the data by interval, then for each interval find the mean number of steps, and plot the results. 
v2 &lt;- aggregate(df$steps, list(df$interval), mean, na.rm=TRUE)
colnames(v2) &lt;- c(&quot;interval&quot;, &quot;ave.steps&quot;)

plot(v2$interval,
     v2$ave.steps,
     type=&quot;l&quot;, 
     ylab=&quot;Average steps taken&quot;, 
     xlab=&quot;Interval&quot;,      
     main=&quot;Average Daily Activity&quot;)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-7-1.png" /></p>
</div>
<div id="which-5-minute-interval-on-average-across-all-the-days-in-the-dataset-contains-the-maximum-number-of-steps" class="section level3">
<h3>2.Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?</h3>
<pre class="r"><code>## find the index of the max value of the vector above
index &lt;-  which.max(v2$ave.steps)

## then use the index to identify the interval it occurs in
interval &lt;- interval.list[index]

## the actual maximum value
maxVal&lt;-signif(max(v2$ave.steps), 3)</code></pre>
<p>The interval across all days which contains the maximum average number of steps is <em>835</em>.</p>
<p>The value of the average number of steps taken during that interval (across all days) is <em>206</em>.</p>
</div>
</div>
<div id="imputing-missing-values" class="section level2">
<h2>Imputing missing values</h2>
<p>There are a number of days/intervals where there are missing values (coded as NA). The presence of missing days may introduce bias into some calculations or summaries of the data.</p>
<div id="calculate-and-report-the-total-number-of-missing-values-in-the-dataset-i.e.the-total-number-of-rows-with-nas" class="section level3">
<h3>1.Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)</h3>
<pre class="r"><code>rows.missing.data&lt;-sum(is.na(df))</code></pre>
<p>There are 2304 rows with missing values in the dataset.</p>
</div>
<div id="devise-a-strategy-for-filling-in-all-of-the-missing-values-in-the-dataset.-the-strategy-does-not-need-to-be-sophisticated.-for-example-you-could-use-the-meanmedian-for-that-day-or-the-mean-for-that-5-minute-interval-etc." class="section level3">
<h3>2.Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.</h3>
<p>Since I previously calculated the mean for each of the intervals above, I used these values to impute the missing data. More specifically, I computed which rows (indices) of the original dataset contained NAs. Then created a new column filled with the average associated with the interval for the row. Finally, for each of the indices of na.indices, replace the steps (NA) with the value in ave.steps.</p>
</div>
<div id="create-a-new-dataset-that-is-equal-to-the-original-dataset-but-with-the-missing-data-filled-in." class="section level3">
<h3>3.Create a new dataset that is equal to the original dataset but with the missing data filled in.</h3>
<pre class="r"><code>#find the indices where steps is NA
na.indices &lt;-which(is.na(df$steps))

# then, using plyr, add the average steps for the interval as a column to the original data set,
# storing the result in temp
temp&lt;-NULL
library(plyr)
temp &lt;- join(df, v2, by=&quot;interval&quot;, type=&quot;left&quot;, match=&quot;all&quot;)

# go through the vector and if $steps is.NA, replace it with $ave.steps


length(temp$steps)</code></pre>
<pre><code>## [1] 17568</code></pre>
<pre class="r"><code>length(temp$ave.steps)</code></pre>
<pre><code>## [1] 17568</code></pre>
<pre class="r"><code>max(na.indices)</code></pre>
<pre><code>## [1] 17568</code></pre>
<pre class="r"><code>temp$steps &lt;- replace(temp$steps, na.indices, temp$ave.steps)</code></pre>
<pre><code>## Warning in replace(temp$steps, na.indices, temp$ave.steps): number of items
## to replace is not a multiple of replacement length</code></pre>
<p>Although R generates a warning with the above code, the computation is ok because the length of both steps and ave.steps are equal and the maximum index in na.index (used to decide which indices to replace) is the size of both arrays (thus not going beyond the end of the buffer.).</p>
</div>
<div id="make-a-histogram-of-the-total-number-of-steps-taken-each-day-and-calculate-and-report-the-mean-and-median-total-number-of-steps-taken-per-day." class="section level3">
<h3>4.Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day.</h3>
<p>Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?</p>
<pre class="r"><code># Calculate the number of steps taken, per day, and put the answers into a vector.
v3 &lt;- aggregate(temp[, 1],list(temp$date), sum)  # na.rm is not needed, there are no more NAs.
colnames(v3) &lt;- c(&quot;date&quot;, &quot;total.steps&quot;)

hist(v3[ , 2], breaks=10, ylab=&quot;Frequency of occurance&quot;, xlab=&quot;Total Steps Reported in the Day (with imputed data)&quot;, 
  main=&quot;Histogram of total number of steps taken each day (with imputed data)&quot;)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-12-1.png" /></p>
<pre class="r"><code># You could use summary here instead to get the answers, but then you can&#39;t plug the answers back into the 
# text below. Doing both here to double check answers
summary(v3$total.steps)[c(3,4)]</code></pre>
<pre><code>## Median   Mean 
##  10770  10770</code></pre>
<pre class="r"><code># don&#39;t display results in scientific notation
options(scipen=999)

new.meanVal &lt;- signif(mean(v3[ , 2]), 4)
new.medianVal &lt;- signif(median(v3[ , 2]), 4)

mean.diff &lt;- meanVal - new.meanVal
median.diff &lt;- medianVal - new.medianVal</code></pre>
<p>Mean:</p>
<p>The mean total number steps taken per day is: <em>10770</em>.</p>
<p>The difference between this value (computed with imputed data) and the original (with NAs removed) is: <em>-1416</em>.</p>
<p>Median:</p>
<p>The median total number steps taken per day is: <em>10770</em>.</p>
<p>The difference between this value (computed with imputed data) and the original (with NAs removed) is: <em>-375</em>.</p>
<p>This shows that imputing the data increases the average and median number of steps results. Using this data in further calculations is more reasonable than using zeros as the data for the NA time periods, as it is more likely the device was turned off than that the person did not take any steps during those times.</p>
</div>
</div>
<div id="are-there-differences-in-activity-patterns-between-weekdays-and-weekends" class="section level2">
<h2>Are there differences in activity patterns between weekdays and weekends?</h2>
<p>The dataset with the filled-in missing values is used for this part.</p>
<div id="create-a-new-factor-variable-in-the-dataset-with-two-levels-weekday-and-weekend-indicating-whether-a-given-date-is-a-weekday-or-weekend-day." class="section level3">
<h3>1.Create a new factor variable in the dataset with two levels, weekday and weekend, <U+0080> indicating whether a given date is a weekday or weekend day.</h3>
<pre class="r"><code>#Continue to use x, with the imputed values.
temp$day&lt;- weekdays(temp$date)

# create a factor of weekday (m-f) and weekend (s-s)
weekdays.idx &lt;- which(!(temp$day == &quot;Saturday&quot; | temp$day == &quot;Sunday&quot;))
weekends.idx &lt;- which(temp$day == &quot;Saturday&quot; | temp$day == &quot;Sunday&quot;)

temp[weekdays.idx, 5] &lt;- &quot;Weekday&quot;
temp[weekends.idx, 5] &lt;- &quot;Weekend&quot;

weekday.data &lt;- temp[ temp$day == &quot;Weekday&quot;, ]
weekend.data &lt;- temp[ temp$day == &quot;Weekend&quot;, ]

# Convert day to a factor, and show that it worked.
temp$day &lt;- as.factor(temp$day)
is.day.factor &lt;- is.factor(temp$day)
day.levels &lt;- levels(temp$day)</code></pre>
<p>The statement, “The day variable in the dataset is a factor.” is TRUE. The levels for the variable are Weekday, Weekend.</p>
</div>
<div id="make-a-panel-plot-containing-a-time-series-plot-i.e.type-l-of-the-5-minute-interval-x-axis-and-the-average-number-of-steps-taken-averaged-across-all-weekday-days-or-weekend-days-y-axis.-see-the-readme-file-in-the-github-repository-to-see-an-example-of-what-this-plot-should-look-like-using-simulated-data." class="section level3">
<h3>2.Make a panel plot containing a time series plot (i.e. type = “l”) of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). See the README file in the GitHub repository to see an example of what this plot should look like using simulated data.</h3>
<pre class="r"><code>temp$ave.steps &lt;- NULL

library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;
## 
## The following objects are masked from &#39;package:plyr&#39;:
## 
##     arrange, count, desc, failwith, id, mutate, rename, summarise,
##     summarize
## 
## The following object is masked from &#39;package:stats&#39;:
## 
##     filter
## 
## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code># calculate the NEW mean steps per interval (per day), based on the updated data, 
temp&lt;-ddply(temp, .(interval, day), mutate, ave.steps = mean(steps))

# and plot the data frame as steps per interval grouped by day in a lattice
library(lattice)
myplot &lt;-xyplot(ave.steps ~ interval | day, 
                groups=day, 
                data = temp, 
                type=&quot;l&quot;, 
                xlab=&quot;Interval&quot;,
                ylab=&quot;Average Steps&quot;,
                layout=c(1, 2) )
print(myplot)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-14-1.png" /></p>
<p>With these plots we can see several things. First, the early daylight hours are, on average, the times of most consistent activity whether on the weekend or weekdays. Secondly, the data shows that on work days activity drops considerably during the day compared to the weekend days where activity seems to be more consistent throughout the day.</p>
</div>
</div>
<div id="end-of-document" class="section level2">
<h2>End of document</h2>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
